
#ifndef RIAK_BUCKET_H
#define RIAK_BUCKET_H

zend_class_entry *riak_ce_riakBucket;

#define RIAK_BUCKET_CLIENT "client"
#define RIAK_BUCKET_CLIENT_LEN strlen(RIAK_BUCKET_CLIENT)

#define RIAK_BUCKET_NAME "name"
#define RIAK_BUCKET_NAME_LEN strlen(RIAK_BUCKET_NAME)



#define RIAK_BUCKET_PROP_ALLOWMULTIPLES "allow_mult"
#define RIAK_BUCKET_PROP_ALLOWMULTIPLES_LEN strlen(RIAK_BUCKET_PROP_ALLOWMULTIPLES)
#define RIAK_BUCKET_CONSTANT_ALLOWMULTIPLES "PROPERTY_ALLOW_MULTIPLES"
#define RIAK_BUCKET_CONSTANT_ALLOWMULTIPLES_LEN strlen(RIAK_BUCKET_CONSTANT_ALLOWMULTIPLES)#
#define RIAK_BUCKET_CONSTANT_ALLOWMULTIPLES_SIZE sizeof(RIAK_BUCKET_CONSTANT_ALLOWMULTIPLES)

#define RIAK_BUCKET_PROP_BIGVCLOCK "big_vclock"
#define RIAK_BUCKET_PROP_BIGVCLOCK_LEN strlen(RIAK_BUCKET_PROP_BIGVCLOCK)
#define RIAK_BUCKET_CONSTANT_BIGVCLOCK "PROPERTY_BIG_VCLOCK"
#define RIAK_BUCKET_CONSTANT_BIGVCLOCK_LEN strlen(RIAK_BUCKET_CONSTANT_BIGVCLOCK)
#define RIAK_BUCKET_CONSTANT_BIGVCLOCK_SIZE sizeof(RIAK_BUCKET_CONSTANT_BIGVCLOCK)

#define RIAK_BUCKET_PROP_CHASHKEYFUN "chash_keyfun"
#define RIAK_BUCKET_PROP_CHASHKEYFUN_LEN strlen(RIAK_BUCKET_PROP_CHASHKEYFUN)
#define RIAK_BUCKET_CONSTANT_CHASHKEYFUN "PROPERTY_CHASH_KEYFUN"
#define RIAK_BUCKET_CONSTANT_CHASHKEYFUN_LEN strlen(RIAK_BUCKET_CONSTANT_CHASHKEYFUN)
#define RIAK_BUCKET_CONSTANT_CHASHKEYFUN_SIZE sizeof(RIAK_BUCKET_CONSTANT_CHASHKEYFUN)

#define RIAK_BUCKET_PROP_LASTWRITEWINS "last_write_wins"
#define RIAK_BUCKET_PROP_LASTWRITEWINS_LEN strlen(RIAK_BUCKET_PROP_LASTWRITEWINS)
#define RIAK_BUCKET_CONSTANT_LASTWRITEWINS "PROPERTY_LAST_WRITE_WINS"
#define RIAK_BUCKET_CONSTANT_LASTWRITEWINS_LEN strlen(RIAK_BUCKET_CONSTANT_LASTWRITEWINS)
#define RIAK_BUCKET_CONSTANT_LASTWRITEWINS_SIZE sizeof(RIAK_BUCKET_CONSTANT_LASTWRITEWINS)

#define RIAK_BUCKET_PROP_LINKFUN "linkfun"
#define RIAK_BUCKET_PROP_LINKFUN_LEN strlen(RIAK_BUCKET_PROP_LINKFUN)
#define RIAK_BUCKET_CONSTANT_LINKFUN "PROPERTY_LINKFUN"
#define RIAK_BUCKET_CONSTANT_LINKFUN_LEN strlen(RIAK_BUCKET_CONSTANT_LINKFUN)
#define RIAK_BUCKET_CONSTANT_LINKFUN_SIZE sizeof(RIAK_BUCKET_CONSTANT_LINKFUN)

#define RIAK_BUCKET_PROP_NVAL "n_val"
#define RIAK_BUCKET_PROP_NVAL_LEN strlen(RIAK_BUCKET_PROP_NVAL)
#define RIAK_BUCKET_CONSTANT_NVAL "PROPERTY_N_VAL"
#define RIAK_BUCKET_CONSTANT_NVAL_LEN strlen(RIAK_BUCKET_CONSTANT_NVAL)
#define RIAK_BUCKET_CONSTANT_NVAL_SIZE sizeof(RIAK_BUCKET_CONSTANT_NVAL)

#define RIAK_BUCKET_PROP_OLDVCLOCK "old_vclock"
#define RIAK_BUCKET_PROP_OLDVCLOCK_LEN strlen(RIAK_BUCKET_PROP_OLDVCLOCK)
#define RIAK_BUCKET_CONSTANT_OLDVCLOCK "PROPERTY_OLD_VCLOCK"
#define RIAK_BUCKET_CONSTANT_OLDVCLOCK_LEN strlen(RIAK_BUCKET_CONSTANT_OLDVCLOCK)
#define RIAK_BUCKET_CONSTANT_OLDVCLOCK_SIZE sizeof(RIAK_BUCKET_CONSTANT_OLDVCLOCK)

#define RIAK_BUCKET_PROP_POSTCOMMIT "postcommit"
#define RIAK_BUCKET_PROP_POSTCOMMIT_LEN strlen(RIAK_BUCKET_PROP_POSTCOMMIT)
#define RIAK_BUCKET_CONSTANT_POSTCOMMIT "PROPERTY_POSTCOMMIT"
#define RIAK_BUCKET_CONSTANT_POSTCOMMIT_LEN strlen(RIAK_BUCKET_CONSTANT_POSTCOMMIT)
#define RIAK_BUCKET_CONSTANT_POSTCOMMIT_SIZE sizeof(RIAK_BUCKET_CONSTANT_POSTCOMMIT)

#define RIAK_BUCKET_PROP_PRECOMMIT "precommit"
#define RIAK_BUCKET_PROP_PRECOMMIT_LEN strlen(RIAK_BUCKET_PROP_PRECOMMIT)
#define RIAK_BUCKET_CONSTANT_PRECOMMIT "PROPERTY_PRECOMMIT"
#define RIAK_BUCKET_CONSTANT_PRECOMMIT_LEN strlen(RIAK_BUCKET_CONSTANT_PRECOMMIT)
#define RIAK_BUCKET_CONSTANT_PRECOMMIT_SIZE sizeof(RIAK_BUCKET_CONSTANT_PRECOMMIT)

#define RIAK_BUCKET_PROP_SMALLVCLOCK "small_vclock"
#define RIAK_BUCKET_PROP_SMALLVCLOCK_LEN strlen(RIAK_BUCKET_PROP_SMALLVCLOCK)
#define RIAK_BUCKET_CONSTANT_SMALLVCLOCK "PROPERTY_SMALL_VCLOCK"
#define RIAK_BUCKET_CONSTANT_SMALLVCLOCK_LEN strlen(RIAK_BUCKET_CONSTANT_SMALLVCLOCK)
#define RIAK_BUCKET_CONSTANT_SMALLVCLOCK_SIZE sizeof(RIAK_BUCKET_CONSTANT_SMALLVCLOCK)

#define RIAK_BUCKET_PROP_YOUNGVCLOCK "young_vclock"
#define RIAK_BUCKET_PROP_YOUNGVCLOCK_LEN strlen(RIAK_BUCKET_PROP_YOUNGVCLOCK)
#define RIAK_BUCKET_CONSTANT_YOUNGVCLOCK "PROPERTY_YOUNG_VCLOCK"
#define RIAK_BUCKET_CONSTANT_YOUNGVCLOCK_LEN strlen(RIAK_BUCKET_CONSTANT_YOUNGVCLOCK)
#define RIAK_BUCKET_CONSTANT_YOUNGVCLOCK_SIZE sizeof(RIAK_BUCKET_CONSTANT_YOUNGVCLOCK)

#define RIAK_BUCKET_PROP_NAME RIAK_BUCKET_NAME
#define RIAK_BUCKET_PROP_NAME_LEN RIAK_BUCKET_NAME_LEN
#define RIAK_BUCKET_CONSTANT_NAME "PROPERTY_NAME"
#define RIAK_BUCKET_CONSTANT_NAME_LEN strlen(RIAK_BUCKET_CONSTANT_NAME)
#define RIAK_BUCKET_CONSTANT_NAME_SIZE sizeof(RIAK_BUCKET_CONSTANT_NAME)

#define RIAK_BUCKET_PROP_R RIAK_CLIENT_R
#define RIAK_BUCKET_PROP_R_LEN RIAK_CLIENT_R_LEN
#define RIAK_BUCKET_CONSTANT_R "PROPERTY_R"
#define RIAK_BUCKET_CONSTANT_R_LEN strlen(RIAK_BUCKET_CONSTANT_R)
#define RIAK_BUCKET_CONSTANT_R_SIZE sizeof(RIAK_BUCKET_CONSTANT_R)

#define RIAK_BUCKET_PROP_RW "rw"
#define RIAK_BUCKET_PROP_RW_LEN strlen(RIAK_BUCKET_PROP_RW)
#define RIAK_BUCKET_CONSTANT_RW "PROPERTY_RW"
#define RIAK_BUCKET_CONSTANT_RW_LEN strlen(RIAK_BUCKET_CONSTANT_RW)
#define RIAK_BUCKET_CONSTANT_RW_SIZE sizeof(RIAK_BUCKET_CONSTANT_RW)

#define RIAK_BUCKET_PROP_W RIAK_CLIENT_W
#define RIAK_BUCKET_PROP_W_LEN RIAK_CLIENT_W_LEN
#define RIAK_BUCKET_CONSTANT_W "PROPERTY_W"
#define RIAK_BUCKET_CONSTANT_W_LEN strlen(RIAK_BUCKET_CONSTANT_W)
#define RIAK_BUCKET_CONSTANT_W_SIZE sizeof(RIAK_BUCKET_CONSTANT_W)

#define RIAK_BUCKET_PROP_DW RIAK_CLIENT_DW
#define RIAK_BUCKET_PROP_DW_LEN RIAK_CLIENT_DW_LEN
#define RIAK_BUCKET_CONSTANT_DW "PROPERTY_DW"
#define RIAK_BUCKET_CONSTANT_DW_LEN strlen(RIAK_BUCKET_CONSTANT_DW)
#define RIAK_BUCKET_CONSTANT_DW_SIZE sizeof(RIAK_BUCKET_CONSTANT_DW)



PHP_METHOD(riakBucket, __construct);

PHP_METHOD(riakBucket, getName);

PHP_METHOD(riakBucket, getR);
PHP_METHOD(riakBucket, setR);

PHP_METHOD(riakBucket, getW);
PHP_METHOD(riakBucket, setW);

PHP_METHOD(riakBucket, getDW);
PHP_METHOD(riakBucket, setDW);

PHP_METHOD(riakBucket, newObject);
PHP_METHOD(riakBucket, getObject);

PHP_METHOD(riakBucket, setProperty);
PHP_METHOD(riakBucket, getProperty);

PHP_METHOD(riakBucket, setProperties);
PHP_METHOD(riakBucket, getProperties);

PHP_METHOD(riakBucket, getKeys);

#endif